# Generated by Django 5.1.3 on 2024-11-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_run_at', models.DateTimeField(editable=False, help_text='Datetime that this scheduled task was previously triggered to run. Copied from `PeriodicTask.last_run_at`.', verbose_name='Last Run Datetime')),
                ('run_at', models.DateTimeField(blank=True, editable=False, help_text='Datetime that this scheduled task was triggered the to run.', null=True, verbose_name='Run Datetime')),
                ('periodic_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('periodic_task', 'previous_run_at'), name='run_instance')],
            },
        ),
    ]
