# Generated by Django 5.1.3 on 2024-11-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0020_runhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runhistory',
            name='previous_run_at',
            field=models.DateTimeField(help_text='Datetime that this scheduled task was previously triggered to run. Copied from `PeriodicTask.last_run_at`.', verbose_name='Last Run Datetime'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='run_at',
            field=models.DateTimeField(blank=True, help_text='Datetime that this scheduled task was triggered the to run.', null=True, verbose_name='Run Datetime'),
        ),
    ]
