# Generated by Django 5.1.3 on 2024-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0021_alter_runhistory_previous_run_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runhistory',
            options={'verbose_name': 'run history', 'verbose_name_plural': 'run histories'},
        ),
        migrations.RemoveConstraint(
            model_name='runhistory',
            name='run_instance',
        ),
        migrations.RemoveField(
            model_name='runhistory',
            name='previous_run_at',
        ),
        migrations.AddField(
            model_name='runhistory',
            name='run_number',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Run count of this triggered task', verbose_name='Run Count'),
        ),
        migrations.AddConstraint(
            model_name='runhistory',
            constraint=models.UniqueConstraint(fields=('periodic_task', 'run_number'), name='run_instance'),
        ),
    ]
